const CONFIG = {
    titleWeb: "Tiêu đề web",
    introTitle: 'Chào mừng Tây đến với buổi khám bệnh',
    introDesc: `Bạn sẽ cần trả lời câu hỏi sau.Thoát ra hoặc ko trả lời đồng nghĩa với việc bạn trả lời là có`,
    btnIntro: 'Ok',
    title: 'Phải chăng bạn bị điên do yêu Phát nhiều quá ?',
    desc: 'Chuẩn chưa ? ',
    btnYes: 'Thích lắmmmmm',
    btnNo: 'Đéo phải',
    question: 'Sao bạn yêu nó',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Vì nó deep trai',
    mess: 'T biết rồi ',
    messDesc: 'Bệnh của bạn đã được xác định để chữa bệnh thì bạn nên tỏ tình với thằng Phát',
    btnAccept: 'Ok luôn',
}
