const CONFIG = {
    titleWeb: "Tiêu đề web",
    introTitle: 'Giang ơi t hỏi mày cái này nha',
    introDesc: `Thoát ra hoặc không trả lời là có đó`,
    btnIntro: 'Ok',
    title: 'Phải chăng mày vẫn yêu con Thương :v',
    desc: 'Đúng không ',
    btnYes: 'Đúng vậy',
    btnNo: 'Đéo còn',
    question: 'Sao lại thế',
    btnReply: 'Gửi cho Thương',
    reply: 'Tao vẫn nhớ nó :(((',
    mess: 'Tao bt mà ',
    messDesc: 'Nói với nó đi',
    btnAccept: 'ok',
}
