const CONFIG = {
    titleWeb: "Tiêu đề web",
    introTitle: 'Em hỏi chị cái này nha',
    introDesc: `Thoát ra hoặc ko trả lời là có`,
    btnIntro: 'Ok',
    title: 'Chị thích em đúng không ?',
    desc: 'Đúng khôngggg ? ',
    btnYes: 'Thích lắmmmmm',
    btnNo: 'Không',
    question: 'Sao chị thích em thế :v',
    btnReply: 'Gửi cho em',
    reply: 'Vì em đẹp trai đóoooooo',
    mess: 'Vậy thì nhắn tin cho em đi còn gì nữa',
    messDesc: 'Nhanh lênnnn',
    btnAccept: 'Ok luôn',
    messLink: 'https://www.facebook.com/messages/t/100070125068608',
    {
